spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./starbucks_kiosk;AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show_sql: true
    database: h2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC